### ISSUE TITLE
Instructions to set up minimal security for elasticsearch

### ISSUE THREAD

**Issue by gunchleoc** [mastodon/documentation#962]
I followed the guide in https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html and ended up with the following settings:

```
discovery.type: single-node

xpack.security.enabled: true

xpack.security.authc:
  anonymous:
    username: anonymous_user
    roles: superuser
    authz_exception: true
```

Should this go into the docs at https://docs.joinmastodon.org/admin/optional/elasticsearch/ ?
